server:
  port: 8081

spring:
  application:
    name: tigetting
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tget?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: tiget
    password: tiget
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ssafy.tigetting.user.entity,com.ssafy.tigetting.entity,com.ssafy.tigetting.venue.entity,com.ssafy.tigetting.queue.entity
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  charset:
    console: UTF-8
    file: UTF-8

jwt:
  secret: ${JWT_SECRET:THIS_IS_A_LONG_RANDOM_PLAIN_SECRET_WITH_32+_CHARS_1234567890abcdef}
  access-token-validity-ms: 3600000

queue:
  max-active-tokens: 1
  max-inactive-seconds: 120
  wait-time-per-person: 10
